const SURVEY_CONFIG = {
  title: "Sutro Li - Introductory Checklist",
  participantCount: "X",
  theme: {
    questionColor: "#000",
    backgroundColor: "#fff",
    accentColor: "#1fb8e9"
  },
  questions: [
    { id: "q1", type: "short_text", title: "Name of Organization: Legal" },
    { id: "q2", type: "short_text", title: "Name of Organization: Bank Account" },
    { id: "q3", type: "short_text", title: "Website" },
    { id: "q4", type: "long_text", title: "Please briefly describe the mission of your organization" },
    { id: "q5", type: "short_text", title: "How did you hear about Sutro Li?" },
    { id: "q6", type: "short_text", title: "Name" },
    { id: "q7", type: "short_text", title: "Direct phone line" },
    { id: "q8", type: "yes_no", title: "Ok to text this number?" },
    { id: "q9", type: "short_text", title: "Email address" },
    { id: "q10", type: "long_text", title: "What is your office address?" },
    { id: "q11", type: "long_text", title: "Please provide the name, title and email of the party who is authorized to sign contracts with new vendors" },
    { id: "q12", type: "multiple_choice", title: "What accounting system do you use?", options: ["Quickbooks Desktop", "Quickbooks Online", "Xero", "No current accounting system", "Other"] },
    { id: "q13", type: "short_text", title: "What is the last day of your fiscal year?" },
    { id: "q14", type: "short_text", title: "What best describes the state of your accounting?" },
    { id: "q15", type: "short_text", title: "What is your next tax filing deadline?" },
    { id: "q16", type: "yes_no", title: "Will you have an annual audit?" },
    { id: "q17", type: "yes_no", title: "Do you have a relationship with a CPA who will conduct your audit or prepare annual filings?" },
    { id: "q18", type: "short_text", title: "Name of CPA firm" },
    { id: "q19", type: "short_text", title: "What bank do you use for checking and savings?" },
    { id: "q20", type: "short_text", title: "What credit card company do you use?" },
    { id: "q21", type: "short_text", title: "What is your projected revenue for the current financial year?" },
    { id: "q22", type: "long_text", title: "What are your primary sources of income? Who are your funders?" },
    { id: "q23", type: "yes_no", title: "Do you have restricted funding?" },
    { id: "q24", type: "long_text", title: "Please describe your restricted funding sources" },
    { id: "q25", type: "yes_no", title: "Do you receive government grants?" },
    { id: "q26", type: "long_text", title: "Please describe your government grant sources" },
    { id: "q27", type: "multiple_choice", title: "What payment methods do you accept?", options: ["Checks", "Paypal", "Credit card payments", "Cash", "Other"] },
    { id: "q28", type: "short_text", title: "Who creates invoices?" },
    { id: "q29", type: "short_text", title: "How are invoices sent to customers?" },
    { id: "q30", type: "short_text", title: "Who makes deposits?" },
    { id: "q31", type: "short_text", title: "How are deposit records currently kept?" },
    { id: "q32", type: "short_text", title: "What is your annual expense budget for the current financial year?" },
    { id: "q33", type: "short_text", title: "Who receives bills?" },
    { id: "q34", type: "short_text", title: "How many bills do you pay in an average month?" },
    { id: "q35", type: "yes_no", title: "Are you looking for support in managing bill payment?" },
    { id: "q36", type: "yes_no", title: "Are you looking for support in issuing bill payment once bills are approved?" },
    { id: "q37", type: "multiple_choice", title: "What bill payment tools do you use?", options: ["Bill.com", "Plooto", "Paypal", "Online Banking ACH", "Online Banking Billpay", "Other"] },
    { id: "q38", type: "short_text", title: "How many credit card users does your organization have?" },
    { id: "q39", type: "short_text", title: "Who has access to credit or debit cards for your company?" },
    { id: "q40", type: "short_text", title: "What payroll service do you use?" },
    { id: "q41", type: "short_text", title: "Other (payroll)" },
    { id: "q42", type: "short_text", title: "Who is authorized to see payroll information?" },
    { id: "q43", type: "short_text", title: "How many employees do you have?" },
    { id: "q44", type: "yes_no", title: "Are you satisfied with your current payroll provider?" },
    { id: "q45", type: "short_text", title: "How have you filed 1099s in the past?" },
    { id: "q46", type: "short_text", title: "How many 1099s do you anticipate filing in the current year? (estimate is fine)" },
    { id: "q47", type: "yes_no", title: "Do you keep inventory?" },
    { id: "q48", type: "yes_no", title: "Do you pay sales tax?" },
    { id: "q49", type: "multiple_choice", title: "What are your priorities?", options: ["We are seeking training in financial procedures for our staff", "Our organization is growing and we need to develop better financial systems to manage our growth", "We're looking to change accounting firms because we are unhappy with our current service provider", "We need outsourced CFO input to help manage the growth or stability of our organization", "We need support preparing for our annual audit", "We would like to improve our budgeting process", "Other"] },
    { id: "q50", type: "long_text", title: "What would an ideal relationship with Sutro Li look like?" },
    { id: "q51", type: "long_text", title: "Please describe any factors driving urgency in this transition" }
  ]
};
